max_width = 90
normalize_comments = true
imports_layout = "Vertical"
imports_granularity = "Crate"
trailing_semicolon = false
edition = "2021"
use_try_shorthand = true
use_field_init_shorthand = true
