[workspace]
resolver = "2"
members = ["apps/*", "libs/common"]
default-members = ["apps/chain-watcher", "apps/assets-indexer", "libs/common"]
exclude = ["apps/.DS_Store"]

[profile.release]
lto = true
panic = "abort"
