[workspace]
resolver = "2"
members = ["apps/*"]
default-members = [
    "apps/chain-watcher",
    "apps/assets-indexer",
]
exclude = [
    "apps/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"